import { CreateUserDto } from './dto/create-user.dto';
import { ChangePasswordDto, ForceChangePasswordDto } from './dto/change-password.dto';
import { UsersService } from './users.service';
export declare class UsersController {
    private readonly usersService;
    constructor(usersService: UsersService);
    findAll(): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }[]>;
    create(dto: CreateUserDto): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    lockUser(id: number): Promise<{
        message: string;
    }>;
    unlockUser(id: number): Promise<{
        message: string;
    }>;
    softDeleteUser(id: number): Promise<{
        message: string;
    }>;
    changeRole(id: number, role: string): Promise<{
        message: string;
    }>;
    updateProfile(req: any, data: any): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    requestEmailChange(req: any, newEmail: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    changePassword(req: any, dto: ChangePasswordDto): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    forceChangePassword(req: any, dto: ForceChangePasswordDto): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    getAddresses(req: any): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }[]>;
    addAddress(req: any, data: any): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }>;
    deleteAddress(req: any, id: number): Promise<import(".prisma/client").Prisma.BatchPayload>;
    updateAddress(req: any, id: number, data: any): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }>;
    setDefaultAddress(req: any, id: number): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }>;
    uploadAvatar(req: any, file: Express.Multer.File): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    deleteOwnAccount(req: any): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    } | null>;
}
