import { PrismaService } from '../prisma/prisma.service';
import { Prisma, Role } from '@prisma/client';
import { CreateUserDto } from './dto/create-user.dto';
export declare class UsersService {
    private prisma;
    create(dto: CreateUserDto): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    constructor(prisma: PrismaService);
    handleCleanUpUnverifiedAccounts(): Promise<void>;
    findByVerificationTokenUsed(token: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    } | null>;
    findOne(email: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    } | null>;
    findDeletedByEmail(email: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    } | null>;
    findById(id: number): Promise<({
        addresses: {
            phone: string;
            id: number;
            userId: number;
            recipientName: string;
            fullAddress: string;
            label: string | null;
            isDefault: boolean;
        }[];
    } & {
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }) | null>;
    findByVerificationToken(token: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    } | null>;
    verifyUserEmail(id: number): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    requestEmailChange(id: number, newEmail: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    findAll(): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }[]>;
    lockUser(id: number): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    unlockUser(id: number): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    softDeleteUser(id: number): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    } | null>;
    changeRole(id: number, role: Role): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    update(id: number, data: Prisma.UserUpdateInput): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    changePassword(id: number, oldPassword: string, newPassword: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    saveResetOtp(email: string, hashedOtp: string, expiry: Date): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    clearResetOtp(email: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    incrementOtpAttempts(email: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    setMustChangePassword(id: number, value: boolean): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    forceChangePassword(id: number, newPassword: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
    getAddresses(userId: number): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }[]>;
    addAddress(userId: number, data: any): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }>;
    deleteAddress(userId: number, addressId: number): Promise<Prisma.BatchPayload>;
    updateAddress(userId: number, addressId: number, data: any): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }>;
    setDefaultAddress(userId: number, addressId: number): Promise<{
        phone: string;
        id: number;
        userId: number;
        recipientName: string;
        fullAddress: string;
        label: string | null;
        isDefault: boolean;
    }>;
    updateAvatar(userId: number, avatarUrl: string): Promise<{
        email: string;
        password: string | null;
        fullName: string | null;
        phone: string | null;
        avatar: string | null;
        role: import(".prisma/client").$Enums.Role;
        isEmailVerified: boolean;
        verificationToken: string | null;
        pendingEmail: string | null;
        resetOtp: string | null;
        resetOtpExpiry: Date | null;
        otpAttempts: number;
        mustChangePassword: boolean;
        isActive: boolean;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        id: number;
    }>;
}
